---
title: "Modelo Matemático - Manufatura Aditiva"
author: "Pedro Nascimento de Lima"
date: "November 19, 2017"
output:
  word_document: default
  pdf_document: 
    latex_engine: xelatex
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


# A Indústria da Manufatura Aditiva


# Modelos de Difusão de Novos Produtos

Falar sobre cada modelo e mostrar o Quadro da análise dos modelos

# Modelo empregado neste Trabalho

Esta seção do trabalho apresenta o modelo de equações diferenciais utilizado para simular o comportamento da indústria da manufatura aditiva.

## Difusão e Demanda por Impressoras 3D.

## Visão Geral do Modelo
O modelo proposto inicialmente por Sterman (XX) foi utilizado como ponto de partida deste trabalho, por possuir uma série de características desejáveis para este trabalho. Em primeiro lugar, o modelo não é restrito a monopólios, como o modelo de Bass (XX) e outros modelos deste trabalho (identificar e citar aqui). Além disso, o modelo possui uma estrutura de dinâmica competitiva considerando a interação de diversos fatores presentes na Indústria da Manufatura Aditiva, incluindo curvas de aprendizagens, diferentes players expandindo sua capacidade produtiva em função da demanda prospectada no mercado.

No modelo proposto por Sterman (XX) dois players, inicialmente com a mesma capacidade produtiva, iniciam vendendo produtos a um mercado em expansão.

## Demanda

A demanda Total da indústria anual $D^T$ é formada pela soma de dois tipos de demanda. A demanda inicial $D^I$ dos produtos (ou seja, à primeira compra realizada por um usuário da impressora 3D), e à demanda oriúnda de recompras $D^R$, realizadas em função do fim da vida útil do equipamento.
$$D^T = D^I + D^R$$
A demanda inicial é calculada $D^I$ em função do número médio de unidades vendidas por clientes $\mu$ e do número de clientes $dA$ que adotou o produto em um intervalo de tempo $dt$:

$$D^I = \mu \frac{dA}{dt}$$

O crescimento do número de clientes $A$ que aderiram às impressoras 3D em um dado instante de tempo $t$ é um estoque modelado por meio do modelo padrão de difusão de Bass (XXXX). Neste modelo o crescimento da população de clientes que aderem à uma ideia é dependente do tamanho total da população $POP$, do número de clientes que não adotaram $N$, da fração de inovadores que adotam ao produto ano a ano independentemente de outros usuários $\alpha$ e do parâmetro $\beta$ que mede a força da difusão do produto por boca-a-boca. A não-negatividade da derivada é garantida obtendo-se o máximo entre a equação e zero.

$$ \frac{dA}{dt}  = MAX\left(0,N \left(\alpha + \beta \frac{A}{POP}\right)\right) $$

O número de consumidores potenciais $N$ é modelado como o máximo entre zero e a diferença entre o número de clientes que irá adotar o produto em algum momento $A^*$ e o número de clientes que adotou o produto $A$.

$$N = MAX(0, A^* - A)$$

O número de clientes que irá adotar o produto $A^*$ é modelado pela equação que calcula a demanda total da indústria, em equilíbrio, e é dependente do preço mínimo do produto $P^{min}$.

$$A^* = MIN \left(POP, POP^r * MAX \left(0, 1+ \frac{\sigma(P^{min} - P^r)}{POP^r}\right)\right)$$

Inclinação da Curva de Demanda:

$$\sigma = - \varepsilon_d \left(\frac{POP^r}{p^r}\right)$$

Demanda por substituição de produtos:

$$D^r = \sum_{i}{D_i} \ ; \ D_i = \delta I_i$$
Installed Base:

$$I_{i,t} = I_{i,t_0} + \int_{t_0}^{t} S_{i,t} - D_{i,t}$$
## Market Share

Orders:
$$O_i = S_i D^T$$

Share:
$$S_i = A_i/\sum_{i}A_i$$

Atratividade: - Aqui deve entrar também a performance do produto.
Standard Logit decision model

$$A_i = e^{\varepsilon_p \frac{P_i}{P^r}} * e^{\varepsilon_a (\frac{B_i}{S_i})/\tau^r}$$

## A Firma

O lucro líquido a valor presente $\pi_{t}$ da firma $i$ é definido como um estoque calculado em função das receitas e custos da empresa, trazidos a valor presente por um fator $\rho$. As receita líquida da empresa é calculada a partir do número de produtos entregues $s_i$ pela empresa $i$ e da diferença entre o preço médio dos produtos entregues $\bar{p_{i}}$, e do seu respectivo custo variável unitário $vc_i$. Os custos fixos da empresa são calculados a partir da sua capacidade $C_{i}$ e de um custo fixo unitário $fc_i$. Desta maneira, o lucro líquido da empresa no tempo $t$ será dado conforme esta equação:

$$ \pi_{t} = \int_{t_0}^{t} [R_i -(C^f_i+C^v_i)]  *  e^{-\rho * t} $$

Receita:
$$R_i = S_{i} * (V_i/B_i)$$

Valor da Carteira de Vendas:
$$V_{i,t} = V_{i,t_0} + \int_{t_0}^{t} P_{i,t}*O_{i,t} - R_{i,t}$$

Custos:

$$C^f_i = u^f_i*K_i\ ; \  C^v_i = u^v_i * S_i$$

Custos Variáveis e Fixos decrescem conforme uma curva de experiência
Standard learning curve:

$$u^f_i = u^f_0(E/E_0)^\gamma ;\ u^v_i = u^v_0(E/E_0)^\gamma  $$

Esta formlua pressupõe que não há troca de experiência entre os players, e que não há "perda de experiência".

$$E_{i,t} = E_{i,t0} + \int_{t_0}^{t} S_i$$

### Produção

Shipmentso é igual à Produção é igual a shipments, desprezando estoques na cadeia produtiva. 

$$Q_i = MIN(Q_i^*,K_i); S_i = Q_i$$

Considera-se um sistema Make to Order, não considera estoques na cadeia. Para eles, o estoque na cadeia introduziria um efeito chicote ainda pior para a estratégia Get big fast, e por isso foi possível desconsidera-lo.

Neste ponto será necessário tomar uma decisão se este aspecto é importante para as estratégias consideradas ou não.


Delivery Delay:

$$\tau_i  = B_i * Q_i$$

"Target Ship Rate:"

$$Q_i^* = B/\tau_i^*$$

Backlog de Produção:

$$B_{i,t} = B_{i,t0} + \int_{t_0}^{t} O_i - Q_i$$

Capacidade: Ajusta-se conforme uma função Erlang Lag de terceira ordem.

Este é o operador $\varphi$ Erlang Lag.

$$K_i = \varphi(K^*,\lambda)$$

Capacidade Alvo e Previsão da Demanda
A capacidade Alvo da Empresa $K^*$ 
market share alvo $S^*$
previsão da demanda $D^*$
taxa de utilização de capacidade $u^*$

$$K^* = MAX(K^{min}, S^*D^e/u^*)$$

mínima escala de produção eficiente $K^{min}$.


Demanda Prevista (Demanda Esperada) $D^e$:
Demanda Observada-Reportada $D^r$
Anos de Previsão $\lambda$
Taxa esperada de crescimento da demanda $g^e$

$$D^e = D^r * e^{\lambda * g^e}$$

Taxa de crescimento da demanda:

Horizonte Histórico usado para a previsão $h$
Demanda Observada-Reportada $D^r$

$$g^e = ln(D^r_t/D^r_t-h)/h$$


Demanda Observada-Reportada $D^r$ - Segue um suavização exponencial:
$$dD^r/dt = (D^T  - D^r)/\tau^r$$
Market Share Alvo e Estratégia da Firma:

$$S^* =  \begin{cases} MAX(S^{min}_i, S^u_i), \ if \ Str_i = Agress. \\ \\ MIN(S^{max}_i, S^u_i), \ if \ Str_i = Conserv. \end{cases}$$

Se a firma busca uma estratégia agressiva, a mesma busca um share dominante do mercado. Uma estratégia conservadora, por outro lado, busca acomodação entre seus rivais, e define um market share modesto.

A empresa agressiva também busca explorar sua vantagem aproveitando-se da demora dos outros players ainda aumentando seu share quando ela identifica que haverá demanda não atendida pelos outros players.


Market Share "Não-Disputado":
$$S^u_i = MAX(0, D^u_i/D^e)$$

Demanda não contestada:

$$D^u_i = D^e - u^* \sum_{j \neq i}K^e_j$$

Capacidade dos competidores esperada:

$$K^e_j = w K^{e^*}_j + (1-w)K_j $$

Calculo da Capacidade com defasagem - segue uma suavização exponencial:

$$dK^{e^*}_j/dt = (K^{*}_j - K^{e^*}_j)/\tau^c$$

Preço:
Preço também ajusta-se a um valor alvo com delay e tempo de ajuste.

$$dP_i/dt = (P^*_i-P_i)/\tau^p$$

Equação do Preço Alvo:

$$P^* = MAX \left[u^v, P \left( 1 + \alpha^c \left( \frac{P^c}{P}-1 \right) \right) \left( 1 + \alpha^d \left( \frac{Q^*}{u^*K}-1 \right)  \right) \left( 1 + \alpha^s \bigg( S^* - S \bigg) \right) \right]$$

Parâmetros, Unidades Valores Máximos e Mínimos:

$$P^C = (1+m^*) (u^f_i + u^f_i)$$
