---
title: Análise RDM Piloto - Modelo de Bass
author:
  - name: Pedro Nascimento de Lima
    email: pedro@example.com
    affiliation: GMAP | UNISINOS
    footnote: Corresponding Author
address:
  - code: Some Institute of Technology
    address: Department, Street, City, State, Zip
abstract: |
  Esta é uma análise piloto utilizando o RDM. Estou usando este documento nesta formatação para integrar os resultados do R dentro do documento sem precisar copiar e colar. No final da análise este texto vai todo para o word. Este documento e análise servirão como um template para a análise "real" do RDM a ser integrada na dissertação, porém deve conter todos os elementos de uma análise RDM.

bibliography: rdmlibrary.bib
output: rticles::elsevier_article
---


Análise RDM Piloto - O Modelo de Bass
==========================

#### Propósito

Este documento apresenta uma análise RDM piloto do modelo de Bass. O objetivo desta análise foi exercitar a aplicação do RDM com um exemplo conhecido pela literatura atual, com o propósito de desenvolver a competência de analisar modelos com o RDM. Neste processo, foi necessário desenvolver algoritmos para a execução e análise dos experimentos computacionais.

O modelo de Bass @Bass1969 é amplamente reconhecido na literatura (frequentemente citado entre os 10 trabalhos mais influentes nos periódicos da INFORMS @, e utilizado por Sterman (2000) e Morecroft (2001) em seus livros a respeito de dinâmica de sistemas).

A análise do modelo de Bass é propícia para este propósito por dois motivos. Primeiro, o modelo representa um dos fatores mais incertos para as empresas privadas: Como será a evolução da demanda de um novo produto. Este modelo foi aplicado em diversas situações, e é capaz de representar processos de crescimento da demanda em novos produtos. Segundo, a execução do modelo depende de parâmetros altamente incertos (ex.: A probabilidade de que um consumidor atual do produto divulgue o produto a outro consumidor).

O Modelo de Bass representa o processo de adoção de novos produtos, e propõe-se a identificar / predizer variáveis importantes para a empresa (ex.: qual será e quando será o pico de vendas de um novo produto?).

Estruturação da Decisão - XLRM
===================

#### X - Incertezas

#### L - Levers (Estratégias)

#### R - Relações (Modelo)

#### M - Métricas

Geração de Casos
===================

#### Projeto de Experimentos Computacionais

#### Tabela de Incertezas

#### Tabela de Estratégias

#### Resultados da Simulação

#### Escolha da Estratégia Candidata

Descoberta de Cenários - Análise de Vulnerabilidades
===================

#### Em que condições a Estratégia Candidata Falha


===================

Once the package is properly installed, you can use the document class
*elsarticle* to create a manuscript. Please make sure that your
manuscript follows the guidelines in the Guide for Authors of the
relevant journal. It is not necessary to typeset your manuscript in
exactly the same way as an article, unless you are submitting to a
camera-ready copy (CRC) journal.

#### Functionality

The Elsevier article class is based on the standard article class and
supports almost all of the functionality of that class. In addition, it
features commands and options to format the

-   document style

-   baselineskip

-   front matter

-   keywords and MSC codes

-   theorems, definitions and proofs

-   lables of enumerations

-   citation style and labeling.

Front matter
============

The author names and affiliations could be formatted in two ways:

(1) Group the authors per affiliation.

(2) Use footnotes to indicate the affiliations.

See the front matter of this document for examples. You are recommended
to conform your choice to the journal you are submitting to.

Bibliography styles
===================

There are various bibliography styles available. You can select the
style of your choice in the preamble of this document. These styles are
Elsevier styles based on standard styles like Harvard and Vancouver.
Please use BibTeX to generate your bibliography and include DOIs
whenever available.

Here are two sample references: @Feynman1963118 [@Dirac1953888].

References {#references .unnumbered}
==========
