---
title: "Capítulo 4 - Versão programada no R."
output: html_notebook
---
Este documento contém a análise v0 aplicando a dinâmica de sistemas e analisando um modelo com o . Este exercício utilizará um modelo de difusão simples (Bass Difussion Model - Bass (1969)).

#### Estruturação da Decisão - XLRM

##### Contextualização
O presente modelo simulará a 

##### X - Incertezas

##### L - Decisões

##### R - Modelo

##### M - Métricas de Medição

#### Geração de Casos

#### Análise dos Casos Gerados

#### Descoberta de cenários

#### Análise de Tradeoffs
Try executing this chunk by clicking the *Run* button within the chunk or by placing your cursor inside it and pressing *Ctrl+Shift+Enter*. 

```{r}
plot(cars)


```

Add a new chunk by clicking the *Insert Chunk* button on the toolbar or by pressing *Ctrl+Alt+I*.

When you save the notebook, an HTML file containing the code and output will be saved alongside it (click the *Preview* button or press *Ctrl+Shift+K* to preview the HTML file).